<a href="https://colab.research.google.com/github/elaamranisoufiane/Resnet50/blob/main/ResNet50.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import os

dataset_path = os.listdir('/content/ResNet50/rooms_dataset')
room_types = os.listdir('/content/ResNet50/rooms_dataset')
#print (room_types)  #what kinds of rooms are in this dataset
print("Types of rooms found: ", len(dataset_path))
print("rooms name", dataset_path)

FileNotFoundError: ignored

In [ ]:
rooms = []

for item in room_types:
 # Get all the file names
 all_rooms = os.listdir('/content/ResNet50/rooms_dataset' + '/' +item)
 #print(all_rooms)
 for room in all_rooms:
   rooms.append((item, str('/content/ResNet50/rooms_dataset' + '/' +item) + '/' + room))
  

NameError: ignored

In [ ]:
for i in rooms:
  print(i)

NameError: ignored

In [ ]:
rooms_df = pd.DataFrame(data=rooms, columns=['room type', 'image'])
print(rooms_df.head())
print(rooms_df.tail())

  room type                                              image
0  bed_room  /content/ResNet50/rooms_dataset/bed_room/thumb...
1  bed_room  /content/ResNet50/rooms_dataset/bed_room/thumb...
2  bed_room  /content/ResNet50/rooms_dataset/bed_room/bed-2...
3  bed_room  /content/ResNet50/rooms_dataset/bed_room/beds-...
4  bed_room  /content/ResNet50/rooms_dataset/bed_room/bedro...
       room type                                              image
388  dining_room  /content/ResNet50/rooms_dataset/dining_room/ch...
389  dining_room  /content/ResNet50/rooms_dataset/dining_room/di...
390  dining_room  /content/ResNet50/rooms_dataset/dining_room/ap...
391  dining_room  /content/ResNet50/rooms_dataset/dining_room/in...
392  dining_room  /content/ResNet50/rooms_dataset/dining_room/th...


In [ ]:
# Let's check how many samples for each category are present
print("Total number of rooms in the dataset: ", len(rooms_df))

 
room_count = rooms_df['room type'].value_counts()

print("rooms in each category: ")
print(room_count)

Total number of rooms in the dataset:  393
rooms in each category: 
bed_room       159
living_room    148
dining_room     86
Name: room type, dtype: int64


In [ ]:

from PIL import Image
# creating a object
img = Image.open('/content/ResNet50/rooms_dataset/bed_room/apartment-2094734__340.jpg')


In [ ]:
import cv2
path = '/content/ResNet50/rooms_dataset/'

im_size = 64

images = []
labels = [] 

for i in room_types:
    data_path = path + str(i)  
    filenames = [i for i in os.listdir(data_path) ]
     
    for f in filenames:
        img = cv2.imread(data_path + '/' + f)  # reading that image as array
        print(img)  # will get the image as an array
        img = cv2.resize(img, (im_size, im_size))
        images.append(img)
        labels.append(i)
labels    

Streaming output truncated to the last 5000 lines.
  [155 150 152]
  [163 157 162]]]
[[[ 31  79 115]
  [ 31  79 115]
  [ 33  81 117]
  ...
  [ 61  82 113]
  [ 62  83 114]
  [ 69  90 121]]

 [[ 28  76 112]
  [ 28  76 112]
  [ 31  79 115]
  ...
  [ 63  84 115]
  [ 64  85 116]
  [ 70  91 122]]

 [[ 31  76 113]
  [ 31  76 113]
  [ 33  78 115]
  ...
  [ 65  86 117]
  [ 65  86 117]
  [ 71  92 123]]

 ...

 [[  7   8  22]
  [  7   8  22]
  [  7   8  22]
  ...
  [ 72  59  45]
  [ 70  57  43]
  [ 71  54  41]]

 [[  7   8  22]
  [  7   8  22]
  [  7   8  22]
  ...
  [ 69  56  42]
  [ 68  55  41]
  [ 70  53  40]]

 [[  7   8  22]
  [  7   8  22]
  [  7   8  22]
  ...
  [ 67  54  40]
  [ 66  53  39]
  [ 69  52  39]]]
[[[ 35  61 137]
  [ 17  59 124]
  [ 76 149 193]
  ...
  [188 179 182]
  [185 174 176]
  [175 164 166]]

 [[ 29  59 130]
  [  3  47 110]
  [ 43 118 162]
  ...
  [168 161 168]
  [131 124 129]
  [110 103 108]]

 [[ 30  67 129]
  [ 41  92 148]
  [ 66 144 187]
  ...
  [ 81  79  91]
  [ 67 

['dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining_room',
 'dining